### ISSUE TITLE
移动空调伴侣X12适配请求

### ISSUE THREAD

**Issue by ghostist** [Caffreyfans/IRbaby#10]
X12使用TYWE3S模块，好像是涂鸦的
与ESP8266不同的地方在于flash大小，TYWE3S只有2M，ESP8266有4M
进入烧录模式也有区别：TYWE3S只需要拉低IO2，ESP8266还需要拉低IO15（运行模式也需要拉低IO15，即IO15始终拉低）
X12使用模块的IO14发送，IO13接收
直接使用IRbaby固件可以烧录，但日志报错内存空间不足，无法创建文件

**Comment by Caffreyfans** [comment]
0.4 版本已适配 X12 设备
