### ISSUE TITLE
HASS里控制，改变模式、风速、扫风，温度均变为17°

### ISSUE THREAD

**Issue by ghostist** [Caffreyfans/IRbaby#12]
条件：
X12刷入0.3.1版本 2Mflash固件，app0.3版本
配置了mqtt 、收发引脚，导出mqtt(因空调不支持，只保留了制冷 制热模式、扫风、风速三类)，接入hass
问题：
在HASS里控制，只要切换模式、风速、扫风任意一项，空调实际均改变温度为17°
例如：当前是制热25大风，扫风关，切换模式为制冷时，HASS界面变为“制冷25 大风，扫风关”，但实际空调为“制冷17°大风 扫风关”

**Comment by Caffreyfans** [comment]
该问题是空调信息未同步造成的，0.5 版本已修复。
