### ISSUE TITLE
apk可否适配android4.4.2以上？

### ISSUE THREAD

**Issue by qianli2017** [Caffreyfans/IRbaby#13]
下载提供的apk无法在android低版本(华为荣耀6，android5.0自带红外遥控器)中安装。请发布apk时可否适配像4.4.2+以上的版本。非常感谢

**Comment by Caffreyfans** [comment]
好的，由于 apk 并未使用到高版 SDK 的特性，可以降低。在下一版本的 release 中我会降低版本。

**Comment by Caffreyfans** [comment]
APP 开发时未考虑到兼容性问题，现 APP 已有太多高 SDK 版本的依赖。暂不开发低版本 APP，准备开发 Web 固件来代替现有 APP 功能。
