### ISSUE TITLE
安卓app点击风扇-艾美特没反应

### ISSUE THREAD

**Issue by a394004149** [Caffreyfans/IRbaby#14]
1.刷完固件，配置好网络之后，无法进入风扇的红外调试，风扇里面基本都不行。
2.在录码界面，对着红外接收器按遥控，app上无任何反应
我换了手机也不行，不知道是哪里的问题

**Comment by Caffreyfans** [comment]
抱歉，这个不是你手机的问题，是我太懒了。现在只支持空调的控制，其他特性都不支持，正在努力开发中。
