### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by flower87lucky** [Caffreyfans/IRbaby#16]
1.我想用你的源码，做一个esp01 512k的固件，我自己加了代码
[env:esp8266-512k-base]
board = ${common.board_512k}
board_build.ldscript = ${common.ldscript_512k}

但是编译时候提示Error: Could not find 'eagle.flash.512k0m1s.ld' LD script in LDPATH 'C:\Users\testuser\Desktop\IRbaby-firmware-0.4\.pio\build\esp8266-512k-base

**Comment by Caffreyfans** [comment]
common.ldscript_512k 变量未定义，问题已解决。
