### ISSUE TITLE
请问三级管事哪一种

### ISSUE THREAD

**Issue by zhaorjgch** [Caffreyfans/IRbaby#2]
您好，请问三级管事哪一种，可以说明一下吗 ，谢谢

**Comment by zsq19958629** [comment]
NPN管子就行了。比如，8050

**Comment by Caffreyfans** [comment]
对于电路这一块，我也不是很理解，学的太少了。这个图我都是在别人的md文档找的...

**Comment by huexpub** [comment]
2N2222  三级管就行，配合5mm 940nm 红外管，
