### ISSUE TITLE
匹配奥克斯空调所有功能键都是开关

### ISSUE THREAD

**Issue by c2726139513** [Caffreyfans/IRbaby#21]
nodemcu刷的0.5版本固件，手机也是装的0.5版本apk，然后设置好mqtt和发射接收针脚，应该都没有问题，就是匹配家里一台奥克斯空调，只有3和10有反应，但是两组遥控都是会出现所有功能键，包括模式、温度加减等按键按下后都会让空调开机或关机，而且在homeassistant里控制也是一样，然后自己录码试过，温度加减和模式什么的应该都可以用，但是这样加在homeassistant里不成一套遥控功能，而且也没有办法匹配当前温度或是模式等，所以想请问这个是奥克斯遥控库的问题吗？如果是的话可以有办法自己录码增加一套遥控吗，如果方便的话能麻烦告知操作方法吗

**Comment by Caffreyfans** [comment]
不行哦，空调是组合码（开关+温度+模式+扫风+风速...），自己录的码只能录到某一状态的红外码。所以你自己录的话是录不出码库的效果的，码库是根据传入空调要控制的状态解出相应的红外码，所以能有比较全的控制效果。

**Comment by Caffreyfans** [comment]
还有你说的按什么模式，温度什么的都会让空调开机，这是我代码设置的。考虑到当控制是关机状态下，如果要开机再设置模式、温度之类的操作就太麻烦了。既然你都准备设置这些了，那肯定要空调开机啊，所以当不是关机操作时，都默认空调开启。

**Comment by c2726139513** [comment]
对的，我自己就是录过几个功能，但是就是出不来码库上有的功能，然后我说的其他的按键什么的不是只会让空调开机，而是开机状态下按就会关机，再按又开机，就是所有键就都跟开关键一样的效果
