### ISSUE TITLE
安卓app搜索不到设备

### ISSUE THREAD

**Issue by luomo1301532** [Caffreyfans/IRbaby#23]

**Comment by luomo1301532** [comment]
安卓设备搜索不到ESP8266，已经完成固件烧录和配网，请问是什么问题

**Comment by Caffreyfans** [comment]
安卓手机跟 ESP8266 是在同一局域网吗？

**Comment by luomo1301532** [comment]
安卓手机和ESP8266是在同一网络

**Comment by Caffreyfans** [comment]
抱歉，目前已定位我是软件问题。今晚修复，谢谢提案。

**Comment by luomo1301532** [comment]
感谢，已经解决。目前发现问题，我在公司的局域网中是搜素不到设备的。建议你搭建一个web，通过websocket，来完成esp8266的配置问题，是一个好的解决方案

**Comment by Caffreyfans** [comment]
确实，我正有此意。我都有 web 开发的提案了。have fun!
