### ISSUE TITLE
海尔立式空调 32组码没有匹配到

### ISSUE THREAD

**Issue by zqh2333** [Caffreyfans/IRbaby#28]

**Comment by Caffreyfans** [comment]
确认下红外信号是否发送，红外信号发送时，用摄像头去拍会看到红光。如果红外信号发送正常，32组码都尝试过则证明确实不能匹配。

**Comment by zqh2333** [comment]
没有光，希望匹配下

**Comment by zqh2333** [comment]
> 确认下红外信号是否发送，红外信号发送时，用摄像头去拍会看到红光。如果红外信号发送正常，32组码都尝试过则证明确实不能匹配。

没有光，希望匹配下

**Comment by Caffreyfans** [comment]
> > 确认下红外信号是否发送，红外信号发送时，用摄像头去拍会看到红光。如果红外信号发送正常，32组码都尝试过则证明确实不能匹配。
> 
> 没有光，希望匹配下

没有光说明你红外发射引脚没设置好啊，或者线没接到。并不是码库的问题。
