### ISSUE TITLE
关于部署在ESP01模块上不能发射红外的问题

### ISSUE THREAD

**Issue by innx2020** [Caffreyfans/IRbaby#30]
首先感谢作者开发如此好用的固件，真的是一键话部署，目前使用的是ESP01模，很小巧，但是只留了0和2两个io，这两个io都是跟启动相关的。io2启动时需要拉高，否则启动会失败，导致接三极管烧毁，提一个小需求能否在下次更新把io口拉低(不知道这样描述是否正确大概就是这个意识)，这样esp01也可以使用。感谢!

**Comment by Caffreyfans** [comment]
好的，请指出具体的 GPIO 引脚，我好更新。

**Comment by innx2020** [comment]
> 好的，请指出具体的 GPIO 引脚，我好更新。

感谢回复。
GPIO0和GPIO2两个io.

**Comment by Caffreyfans** [comment]
好的，今晚会更新。

**Comment by Caffreyfans** [comment]
现在启动拉低了 gpio2
