### ISSUE TITLE
固件启动成功wifi配置成功，打开app闪退

### ISSUE THREAD

**Issue by innx2020** [Caffreyfans/IRbaby#31]
模块：esp-12e
接线：vcc3.3v，rst、en高电平，gpio15、gnd低电平。启动正常
固件：0.9
APP：0.9 （安卓4.4.4、安卓10均已尝试）
使用网页配置wifi，打开app可以在设备管理发现，设置mqtt，端口。发射引脚14，接受引脚10。
以上步骤均正常。
点击家电控制-点击设备-空调-选择 格力，到这一步app白屏或者闪退报错。
望回复。感谢！

**Comment by Caffreyfans** [comment]
那请先使用 0.8 版本，0.9 版本我会再进行测验。

**Comment by innx2020** [comment]
已发现问题所在，mqtt为自建没有用户名密码，用户密码为空app即会闪退，填写任意用户名密码即可正常使用。
关闭issues。

再次感谢开发者的辛苦创作。

**Comment by Caffreyfans** [comment]
抱歉这是我程序的 bug
