### ISSUE TITLE
添加完了之后 在HA中调温制热自动变成制冷

### ISSUE THREAD

**Issue by wuyuanqing21** [Caffreyfans/IRbaby#34]
添加完了之后 在HA中调温制热自动变成制冷

**Comment by wuyuanqing21** [comment]
用的是最新的app
mqtt端口不设置 加完设备之后

**Comment by Caffreyfans** [comment]
没搞懂, HA 跟设备之间是 MQTT 通信的,如果 MQTT 端口没设置按道理说是不能通信的啊.

如果方便的话,请附带上设置前和设置后,ESP8266 串口打印出来的数据供参考.

**Comment by wuyuanqing21** [comment]
我是把端口先设置成零 匹配好空调   然后再去设置端口  不然app闪退

**Comment by Caffreyfans** [comment]
> 我是把端口先设置成零 匹配好空调 然后再去设置端口 不然app闪退

好的,这样操作是没问题的.现在的问题是解决 HA 控制与实际反映效果不一致的问题,方便贴出串口打印信息吗?
