### ISSUE TITLE
请问一下根据命令码，如何确定载波呢?

### ISSUE THREAD

**Issue by chenliuyun** [Caffreyfans/IRbaby#35]
你好，通过红外管发送时间码的时候，载波是怎么确定的呢? 还是默认是38K嘛。
不好意思对嵌入式不太熟悉。目前正在查看 irext 的提供的数据库，但是还是无法看到相关的信息，请问是怎么处理该问题的了，多谢了

**Comment by Caffreyfans** [comment]
一般电器都是 38K 载波,其他频率的暂时还没遇到过. 所以用默认的就好了.
