### ISSUE TITLE
ESP8285能用吗

### ISSUE THREAD

**Issue by StephenBen** [Caffreyfans/IRbaby#39]
在网上找到有些把红外发射接收和ESP8285集成在一个板子上的，想看看能不能刷在这种板子上刷这些固件，或者有什么方法可以使得8285支持IRBaby

**Comment by Caffreyfans** [comment]
可以的，ESP8285 是兼容 ESP8266 的。

**Comment by StephenBen** [comment]
好的，谢谢！
