### ISSUE TITLE
请问接收二极管如果是长短两针是否是长针接数据，短针接gnd，我按如上接法信号录制没有反应。

### ISSUE THREAD

**Issue by wwenr** [Caffreyfans/IRbaby#41]

**Comment by Caffreyfans** [comment]
你好,红外发射管和红外接收管是两种器件.你可以在淘宝上搜索下红外接收管.

**Comment by wwenr** [comment]
> 你好,红外发射管和红外接收管是两种器件.你可以在淘宝上搜索下红外接收管.

我手里只有5mm的两脚红外接收管，接上后信号录制没反应（接的D5，按照引脚定义软件配置里填的14号），是否是只支持3脚红外接收管？

**Comment by Caffreyfans** [comment]
红外接收管只有接收作用，发射管只有发射作用。所以你用红外发射管去接收红外信号是不可行的。需要使用三脚的红外接收管才行。

**Comment by wwenr** [comment]
> 红外接收管只有接收作用，发射管只有发射作用。所以你用红外发射管去接收红外信号是不可行的。需要使用三脚的红外接收管才行。

好的，感谢大佬

**Comment by Caffreyfans** [comment]
如果没有什么问题，我就关闭这个 issue 了。

**Comment by Caffreyfans** [comment]
> > 红外接收管只有接收作用，发射管只有发射作用。所以你用红外发射管去接收红外信号是不可行的。需要使用三脚的红外接收管才行。
> 
> 好的，感谢大佬

记得点个 star

**Comment by wwenr** [comment]
> > > 红外接收管只有接收作用，发射管只有发射作用。所以你用红外发射管去接收红外信号是不可行的。需要使用三脚的红外接收管才行。
> > 
> > 
> > 好的，感谢大佬
> 
> 记得点个 star

嘿嘿 一定
