### ISSUE TITLE
HomeAssistant中无法自动发现，手动添加也不行

### ISSUE THREAD

**Issue by Ljzd-PRO** [Caffreyfans/IRbaby#42]
HomeAssistant中没有自动发现设备，查看被忽略的集成里也没有。手动添加MQTT的话，显示“无法连接到服务器。”，是否是账号密码还是端口输入错误，我端口号填的是默认的1883，账号和密码留空。另外，在安卓客户端中是可以进行控制的

**Comment by Caffreyfans** [comment]
账户、密码先不留空。如果你是空账户，你可以随意填写一个账户进去，但是不好留空试试。这个程序的一个 bug 一直未修复。
