### ISSUE TITLE
请问红外收发器可以用TTL通讯的吗？

### ISSUE THREAD

**Issue by Ljzd-PRO** [Caffreyfans/IRbaby#44]
该红外收发器有5V、TXD、RXD、GND接口，经过测试发现，将TXD连接到开发板对应的红外接收GPIO口，RXD连接到开发板对应的红外发射GPIO口，在安卓客户端中可以收到红外收发器收到的红外信号，但是无法发射信号。
使用VCC、GND、DAT接口的红外收发器则可以正常收发，但是市面上这类产品大多发射距离短。
![IMG_7160](https://user-images.githubusercontent.com/63289359/151169100-4220f678-690c-467e-bf97-d00273634879.JPG)

**Comment by Caffreyfans** [comment]
请阅读该收发器手册，它是否内部有处理器来发射红外信号。也就是说外部只是给它下发指令，红外信号由它解析命令后发送，如果是这样的收发器就不可以。

**Comment by Ljzd-PRO** [comment]
好的
